name: Build
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      run: |
        CGO_ENABLED=0 GOARCH=amd64 GOOS=darwin go build -o beihangLogin.darwin.amd64 .
        CGO_ENABLED=0 GOARCH=amd64 GOOS=freebsd go build -o beihangLogin.freebsd.amd64 .
        CGO_ENABLED=0 GOARCH=386 GOOS=freebsd go build -o beihangLogin.freebsd.386 .
        CGO_ENABLED=0 GOARCH=amd64 GOOS=linux go build -o beihangLogin.linux.amd64 .
        CGO_ENABLED=0 GOARCH=386 GOOS=linux go build -o beihangLogin.linux.386 .
        CGO_ENABLED=0 GOARCH=arm GOOS=linux go build -o beihangLogin.linux.arm .
        CGO_ENABLED=0 GOARCH=arm64 GOOS=linux go build -o beihangLogin.linux.arm64 .
        CGO_ENABLED=0 GOARCH=mips GOOS=linux go build -o beihangLogin.linux.mips .
        CGO_ENABLED=0 GOARCH=mips64 GOOS=linux go build -o beihangLogin.linux.mips64 .
        CGO_ENABLED=0 GOARCH=mips64le GOOS=linux go build -o beihangLogin.linux.mips64le .
        CGO_ENABLED=0 GOARCH=mipsle GOOS=linux go build -o beihangLogin.linux.mipsle .
        CGO_ENABLED=0 GOARCH=amd64 GOOS=windows go build -o beihangLogin.windows.amd64 .
        CGO_ENABLED=0 GOARCH=386 GOOS=windows go build -o beihangLogin.windows.386 .
